### ISSUE TITLE
Review proposals posted for TAG design reviews?

### ISSUE THREAD

**Issue by littledan** [nodejs/open-standards#10]
Which open standards should this group be looking at? One source would be, proposals that someone has expressed interest in using in Node.js. A more systematic way might be to look at what's shipping in browsers, or proposed to be shipping soon.

[TAG design review requests](https://github.com/w3ctag/design-reviews/issues) give one view on that--the Blink intent-to-ship process requires a TAG review request, so reviewing these requests as they come out will help Node to give feedback at the exact time that proposal authors are seeking it.

**Comment by slightlyoff** [comment]
Got here from a pointer by @kenchris. Hope I'm not out of place!

With my TAG hat on, would suggest that the JS/TC39 think of the TAG as a way to help accelerate use of late-stage features in DOM and align new API designs around the latest available patterns enabled by modern JS.

We successfully helped accelerate Promises and Constructors adoption by serving as a forum that prompted many new designs to align with them. We are currently doing this for Streams. We'd like to be help improve adoption and consistency with other new features that come along.

A good way to do this is, perhaps, to give us a "head's up" on features that reach Stage 3 which you expect would have value if adopted by DOM APIs. That could be a regular liason, a review request, or some other mechanism. We're not super picky!

**Comment by littledan** [comment]
@slightlyoff Note, this purpose of this repository is for Node.js to give feedback into proposed standards, not for TC39 to interact with the TAG. What do you think would be the right point for Node give that feedback?

**Comment by MylesBorins** [comment]
I've tagged https://github.com/nodejs/node/pull/21551 for tag review 🎉

**Comment by littledan** [comment]
Hmm, I feel like I didn't explain myself clearly in the first post. I'm not suggesting that we put Node things up for TAG review, but that we use TAG's review queue as a guide to what Node could consider reviewing.
