### ISSUE TITLE
Call to discuss TC39 issues?

### ISSUE THREAD

**Issue by littledan** [nodejs/open-standards#14]
Would anyone be interested in having an call some time to discuss new JavaScript language features under discussion at TC39 and how they would relate to Node.js? I'd be really interested in getting your input on whatever you have thoughts on, or answer any questions you have. The discussion could be in the style of the existing educator and framework calls, which you can learn more about at https://github.com/littledan/js-outreach-groups .

**Comment by joyeecheung** [comment]
I am interested! From https://github.com/littledan/js-outreach-groups I think it'll mainly focus on learning more about stage-3 proposals and collecting feedback on stage-2 proposals?

cc @nodejs/open-standards , maybe some folks from @nodejs/tsc  would be interested as well (I dare not to ping the whole collaborators team but I guess people who are interested will probably notice this issue..)

**Comment by littledan** [comment]
> From https://github.com/littledan/js-outreach-groups I think it'll mainly focus on learning more about stage-3 proposals and collecting feedback on stage-2 proposals?

Also interested in discussing feedback on proposals which aren't yet at Stage 2, and even things that TC39 should be looking into but isn't yet.

How about we try to make this happen in the 2nd or 3rd week of January? That should give us significant time to find a time and make an agenda. To get started, let's start brainstorming agenda items here.

**Comment by devsnek** [comment]
I'd love to join

**Comment by MylesBorins** [comment]
Count me in

**Comment by bmeck** [comment]
Sounds good to me, I'd agree having this prior to TC39 meetings rather than after would be ideal.

**Comment by ljharb** [comment]
Same

**Comment by mcollina** [comment]
I'd love to join as well

**Comment by littledan** [comment]
It's always both prior to and after TC39 meetings! There are so many TC39 meetings and so many topics to cover that I don't thing we have to really synchronize.

**Comment by thefourtheye** [comment]
I would like to join as well.

**Comment by littledan** [comment]
OK, please sign up on this Doodle if you're interested: https://doodle.com/poll/kf5nezucerdpfmbr

**Comment by targos** [comment]
I'm also interested. I filled the Doodle.

**Comment by fraxken** [comment]
I'm interested if the talk is not restricted to the Node.js members :) (already registered on doodle).

**Comment by littledan** [comment]
I see no particular reason to restrict call attendance at this point. If more than 20-30 people sign up for it, we should think about breaking into multiple, smaller discussions so that everyone can have space to give their feedback, but we're not at that point yet.

**Comment by Bamieh** [comment]
I would love to join!

**Comment by littledan** [comment]
Please sign the Doodle if you would like to join.

**Comment by ljharb** [comment]
@littledan all the times are on the hour; any chance for some times on the half hour in the same window?

**Comment by littledan** [comment]
@ljharb Several people have already signed the Doodle. I think it's a bit late to add additional options.

**Comment by mhdawson** [comment]
I'm interested.

**Comment by littledan** [comment]
OK, invites sent, see you all next week, January 7th at 17:00 UTC! Google Meet link: https://meet.google.com/jyn-gedh-pbs . Let me know if you want an invite and didn't receive one.

**Comment by littledan** [comment]
Thanks for joining this call! We decided to not have recurring meetings, and coordinate next steps in this repository.

**Comment by thefourtheye** [comment]
Thanks for organising this @littledan.
