### ISSUE TITLE
Hunting for ECMAScript proposals that may be interesting to Node

### ISSUE THREAD

**Issue by joyeecheung** [nodejs/open-standards#16]
An idea from the call (https://github.com/nodejs/open-standards/issues/14): going through the [list of current proposals](https://github.com/tc39/proposals), find those that may be interesting to Node Core, and create a list in this repo with useful info e.g.

- How to get involved (issue tracker, champion to contact, etc.)
- Why they are relevant to Node, e.g. APIs or subsystems that may be affected, or have the new feature integrated, or be made obsolete, or need care in terms of interop
- Links to previous discussions and relevant issues

When we have enough momentum and discussion around a specific topic, the participants can setup calls when they think it's time to have a call. If they start to have ongoing work on this topic, they could setup regular calls and try to sync with TC39 meetings (e.g. brief to champions or other delegates so their discussions are reflected in the meetings) if they think that's helpful.

Some proposals that may need further investigation:

- Temporal
- Built-in modules
- Top-level await
- Zones
- Realms
- Observables 

This is an issue to start the bootstrapping work on this (figure out what the list would be, maybe PR it into this repo at some point)

Preferably we should be looking at proposals no later than stage 2 as there's more room to experiment with them.

**Comment by mhdawson** [comment]
If we have somebody who has ramped up on one of these I'm wondering if it would be good to have an overview presented at TSC meetings (when we have a light agenda). That would help bring more people up to speed, not only TSC members but also people who watch the meeting live or as a recording later on.

**Comment by MylesBorins** [comment]
@mhdawson I regularly attend the meetings and have some context. The entire agenda is public. What may make the most sense is having the open standards group host a pre-meeting to review agenda and identify proposals of interest. Those highlights could be presented to TSC

**Comment by littledan** [comment]
I'd be happy to give these sorts of overviews as well if it's useful.

**Comment by littledan** [comment]
If folks would be interested in a call to discuss any of these proposals, or others, I'd be happy to host one in September or October 2019. Let's discuss this possibility at https://github.com/openjs-foundation/standards-wg/issues/4 .
