### ISSUE TITLE
Idea: Open Standards Session at Collaborator Summit in May

### ISSUE THREAD

**Issue by jorydotcom** [nodejs/open-standards#18]
Hey all, @mcollina & I just had this thought that we should grab session time to discuss the OpenJS Foundation's standards work across Node and JSF projects. We can talk about how the JSF managed this in the past, what we did, and the Node projects efforts/interests in this area. 

I'd be happy to co-host this session - anyone interested?

related: [link to cfp form](https://forms.gle/7kVLuUz2NxviCTmWA)

**Comment by mhdawson** [comment]
Sounds good to me.

**Comment by MylesBorins** [comment]
Very interested

**Comment by benjamingr** [comment]
Also would love to hear this

**Comment by jorydotcom** [comment]
Groovy - I can take care of submitting the form, does anyone want to co-host?

**Comment by jorydotcom** [comment]
FYI I submitted a session proposal for this!

**Comment by littledan** [comment]
I'm wondering, what if we had two sessions: One high-level one with the agenda that @jorydotcom described above, and a separate one to review TC39 proposals? Would folks be interested in the second one? If so, I'd be happy to run it.

**Comment by MylesBorins** [comment]
I would be interested in both

**Comment by mcollina** [comment]
+1

Il giorno mar 14 mag 2019 alle ore 18:51 Myles Borins <
notifications@github.com> ha scritto:

**Comment by benjamingr** [comment]
@littledan I'd love to attend

**Comment by littledan** [comment]
Great; I have submitted a proposal for this.

**Comment by jorydotcom** [comment]
+1! thanks @littledan !

**Comment by tniessen** [comment]
I believe this can be closed, feel free to reopen if you disagree.
