### ISSUE TITLE
How does Node.js communicate feedback on TC39 spec proposals?

### ISSUE THREAD

**Issue by benjamingr** [nodejs/open-standards#6]
There have been cases in the past where earlier feedback from Node.js to TC39 and better coordination could have saved us a lot of time.

 - How should Node.js track proposals to TC39 that relate to us?
 - Would it make sense for project members involved in TC39 to provide updates to various project teams?
 - Should there be a formal'ish process for Node.js members to request changes and spec amendments? (or better - raise the problems themselves)

**Comment by MylesBorins** [comment]
The agenda for each meeting is public, we could likely schedule a team meeting for a week before the tc39 meeting to review the agenda and make notes about where people sit.

If we have a delegate representing node itself they can attend and ensure those view points are represented. In the mean time before we have an official delegate for the project this can be handled by individuals already attending.

For specific proposals between meetings the best way to engage is on the issue tracker of the proposal itself. I'll let some of the more seasoned committee members lmk if I'm wrong.

We can always invite the champion of a proposal to come to meeting if we want to discuss things at length

**Comment by littledan** [comment]
Engaging on the GitHub issue tracker for proposal repositories is a really great way to be involved, and I'd strongly recommend it where possible.

To supplement that, I like the idea of these meetings before TC39 to discuss proposals. Sometimes, it can be hard for people to participate with issues on GitHub, and these meetings together with solid notes could be a great resource. From there, we could follow up with presenting these views in the TC39 meeting, filing issues in GitHub based on the discussion, and/or distributing the notes directly to proposal champions.

Happy to help with describing proposals, their state, and motivation, in these meetings. If anyone has questions about anything related to TC39, feel free to ask me.
