### ISSUE TITLE
For other who are interested?

### ISSUE THREAD

**Issue by SMotaal** [nodejs/open-standards#7]
I am very interested in **open** and **standards**. So for me I think I love the idea of a @nodejs/open-standards effort. Sounds about right? Hope there is room for more of us on board.

If so, I hope this issue evolves into the "if you are interested, read this, then…" entry for this repo.  I will wait for feedback from current members, and take time to catch up on the other threads.

**Comment by sendilkumarn** [comment]
I am interested too 😁

**Comment by jorydotcom** [comment]
Me also 😄

**Comment by bterlson** [comment]
Me four!

**Comment by joyeecheung** [comment]
Refs: https://github.com/nodejs/open-standards/issues/9

**Comment by boazsender** [comment]
I am also interested in this topic :D/
